"""empty message

Revision ID: 2e4965dfe9a9
Revises: a2f50a06e313
Create Date: 2022-04-10 17:18:56.566411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4965dfe9a9'
down_revision = 'a2f50a06e313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=640), nullable=True),
    sa.Column('mthd', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_mthd'), 'answers', ['mthd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_mthd'), table_name='answers')
    op.drop_table('answers')
    # ### end Alembic commands ###
