"""empty message

Revision ID: a2f50a06e313
Revises: c0cad3148e27
Create Date: 2022-04-10 16:29:18.006838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f50a06e313'
down_revision = 'c0cad3148e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responces', sa.Column('type', sa.String(length=1), nullable=True))
    op.drop_index('ix_responces_type', table_name='responces')
    op.create_index(op.f('ix_responces_type'), 'responces', ['type'], unique=False)
    op.drop_column('responces', 'mthd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responces', sa.Column('mthd', sa.VARCHAR(length=1), nullable=True))
    op.drop_index(op.f('ix_responces_type'), table_name='responces')
    op.create_index('ix_responces_type', 'responces', ['mthd'], unique=False)
    op.drop_column('responces', 'type')
    # ### end Alembic commands ###
