"""responces table

Revision ID: c0cad3148e27
Revises: 8483f7d7e41b
Create Date: 2022-04-10 11:17:50.324677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cad3148e27'
down_revision = '8483f7d7e41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('responce', sa.String(length=640), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responces_type'), 'responces', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responces_type'), table_name='responces')
    op.drop_table('responces')
    # ### end Alembic commands ###
